version: "3"

services:
  mycontainer:
    image: {REPO}/{CONTAINER}:{TAG}
    network_mode: host
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - '3000:3000'
      - '4000:4000/udp'
    environment:
      - ENV_VAR=value
    volumes:
      - /etc/localtime:/etc/localtime:ro
  mycontainer2:
    image: {REPO}/{CONTAINER}:{TAG}
    restart: unless-stopped
    expose:
      - '3000'
    depends_on:
      - mycontainer
    volumes:
      - /etc/localtime:/etc/localtime:ro