include:
  - config/plugins/plugins.yaml
  - config/ui.yaml

########## Global
library: /config/library.sqlite3.db
directory: /data/media/music
ignore: [".*", "*~", "System Volume Information"]
ignore_hidden: yes
replace:
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '[\xE8-\xEB]': e
  '[\xEC-\xEF]': i
  '[\xE2-\xE6]': a
  '[\xF2-\xF6]': o
  '[\xF8]': o
  '\.$': _
  '\s+$': ''
asciify_paths: no
art_filename: coverart
threaded: yes
format_item: '$artist - $album - $title'
format_album: '$albumartist - $album'
sort_item: 'artist+ album+ disc+ track+'
sort_album: 'albumartist+ album+'
sort_case_insensitive: no
original_date: no
artist_credit: no
per_disc_numbering: yes
va_name: 'Various Artists'

########## UI
ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: purple
    text_highlight_minor: fuchsia
    action_default: turquoise
    action: green

######### Import
import:
  write: yes
  copy: no
  move: yes
  link: no
  hardlink: no
  resume: ask
  incremental: no
  incremental_skip_later: yes
  from_scratch: no
  quiet_fallback: skip
  none_rec_action: ask
  timid: yes
  log: /config/import.log
  default_action: apply
  # An empty list will prefer the artist's language
  languages: []
  # only show changes
  detail: yes
  autotag: yes
  duplicate_action: ask
  bell: yes

########## Music Brainz
musicbrainz:
  searchlimit: 5

########## Auto-tagger
match:
  strong_rec_thresh: 0.04 # 99.6%
  #ignored: missing_tracks
  #preferred:
  #  media: ['CD', 'Digital Media|File']
  #  original_year: yes

########## Paths
paths:
  default: $albumartist/$album%aunique{albumartist album,albumtype year label catalognum albumdisambig, ()}/$disc-$track $title
  singleton: Non-Album/$artist - $title
  comp: Compilations/$album%aunique{albumartist album,albumtype year label catalognum albumdisambig, ()}/$disc-$track $title
  albumtype:soundtrack: Soundtracks/$album%aunique{albumartist album,albumtype year label catalognum albumdisambig, ()}/$disc-$track $title

########## Plugins
plugins: acousticbrainz badfiles bpd chroma convert duplicates edit embedart export fetchart fromfilename ftintitle fuzzy info lastgenre random replaygain rewrite scrub types web

acousticbrainz:
  auto: yes
  force: no
  # empty list is all tags
  tags: []
bpd:
  host: 0.0.0.0
  port: 6600
  password: <PASSWORD>
  volume: 100
chroma:
  auto: yes
convert:
  auto: no
  copy_album_art: no
  album_art_maxwidth: 500
  embed: yes
  never_convert_lossy_files: yes
  ffmpeg: /usr/bin/ffmpeg
  opts: -ab 320k -ac 2 -ar 48000
  max_bitrate: 320
embedart:
  auto: yes
  ifempty: yes
  maxwidth: 500
  remove_art_file: no
export:
  json:
    formatting:
      ensure_ascii: False
      indent: 2
      separators: [',' , ': ']
      sort_keys: true
fetchart:
  auto: yes
ftintitle:
  auto: yes
  drop: no
  format: '(Featuring {0})'
fuzzy:
  threshold: 0.7
  prefix: '~'
lastgenre:
  auto: yes
  source: album
  count: 1
  fallback: NO_GENRE
  force: no
  min_weight: 10
plex:
  host: localhost
  port: 32400
  token: <TOKEN>
replaygain:
  auto: no
  overwrite: no
scrub:
  auto: yes
types:
  rating: int
web:
  host: 0.0.0.0
  port: 8337
  reverse_proxy: yes